import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'production', 'test').default('development'),
  PORT: Joi.number().default(4000),
  APP_NAME: Joi.string().required(),
  COOKIE_PREFIX: Joi.string().required(),
  DATABASE_URL: Joi.string().required(),
  DIRECT_URL: Joi.string().required(),
  JWT_ACCESS_SECRET: Joi.string().min(16).required(),
  JWT_REFRESH_SECRET: Joi.string().min(16).required(),
  OTP_JWT_SECRET: Joi.string().min(16).required(),
  INVITE_TOKEN_SECRET: Joi.string().min(16).required(),
  PREVIEW_TOKEN_SECRET: Joi.string().min(16).required(),
  COOKIE_SECRET: Joi.string().min(16).required(),
  CORS_ORIGINS: Joi.string().allow('').default(''),
  GOOGLE_CLIENT_ID: Joi.string().allow('').default(''),
  GOOGLE_CLIENT_SECRET: Joi.string().allow('').default(''),
  GOOGLE_CALLBACK_URL: Joi.string().allow('').default(''),
  CLOUDINARY_CLOUD_NAME: Joi.string().required(),
  CLOUDINARY_API_KEY: Joi.string().required(),
  CLOUDINARY_API_SECRET: Joi.string().required(),
  CLOUDINARY_FOLDER: Joi.string().allow('').default(''),
  MAIL_HOST: Joi.string().default('smtp.gmail.com'),
  MAIL_PORT: Joi.number().default(465),
  MAIL_USER: Joi.string().allow('').default(''),
  MAIL_PASS: Joi.string().allow('').default(''),
  MAIL_FROM: Joi.string().allow('').default(''),
  ADMIN_NOTIFY_EMAIL: Joi.string().allow('').default(''),
  BULKSMSBD_API_KEY: Joi.string().allow('').default(''),
  BULKSMSBD_SENDER_ID: Joi.string().allow('').default(''),
  PUBLIC_SITE_URL: Joi.string().required(),
  SEED_ADMIN_EMAIL: Joi.string().email().required(),
  SEED_ADMIN_PHONE: Joi.string().required(),
  SEED_ADMIN_PASSWORD: Joi.string().min(8).required(),
});
