import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'production', 'test').default('development'),
  PORT: Joi.number().default(4000),
  APP_NAME: Joi.string().required(),
  COOKIE_PREFIX: Joi.string().required(),
  DATABASE_URL: Joi.string().required(),
  DIRECT_URL: Joi.string().required(),
  JWT_ACCESS_SECRET: Joi.string().min(16).required(),
  JWT_REFRESH_SECRET: Joi.string().min(16).required(),
  OTP_JWT_SECRET: Joi.string().min(16).required(),
  INVITE_TOKEN_SECRET: Joi.string().min(16).required(),
  PREVIEW_TOKEN_SECRET: Joi.string().min(16).required(),
  COOKIE_SECRET: Joi.string().min(16).required(),
  CORS_ORIGINS: Joi.string().allow('').default(''),
  GOOGLE_CLIENT_ID: Joi.string().allow('').default(''),
  GOOGLE_CLIENT_SECRET: Joi.string().allow('').default(''),
  GOOGLE_CALLBACK_URL: Joi.string().allow('').default(''),
  CLOUDINARY_CLOUD_NAME: Joi.string().required(),
  CLOUDINARY_API_KEY: Joi.string().required(),
  CLOUDINARY_API_SECRET: Joi.string().required(),
  CLOUDINARY_FOLDER: Joi.string().allow('').default(''),
  MAIL_HOST: Joi.string().default('smtp.gmail.com'),
  MAIL_PORT: Joi.number().default(465),
  MAIL_USER: Joi.string().allow('').default(''),
  MAIL_PASS: Joi.string().allow('').default(''),
  MAIL_FROM: Joi.string().allow('').default(''),
  ADMIN_NOTIFY_EMAIL: Joi.string().allow('').default(''),
  BULKSMSBD_API_KEY: Joi.string().allow('').default(''),
  BULKSMSBD_SENDER_ID: Joi.string().allow('').default(''),
  PUBLIC_SITE_URL: Joi.string().required(),
  SEED_ADMIN_EMAIL: Joi.string().email().required(),
  SEED_ADMIN_PHONE: Joi.string().required(),
  SEED_ADMIN_PASSWORD: Joi.string().min(8).required(),
  GEMINI_API_KEY: Joi.string().allow('').default(''),
  GEMINI_TEXT_MODELS: Joi.string().allow('').default(
    'gemini-3.5-flash,gemini-3.1-pro-preview,gemini-3.1-flash-lite,gemini-2.5-pro,gemini-3-flash-preview',
  ),
  GEMINI_IMAGE_MODELS: Joi.string().allow('').default(
    'gemini-2.5-flash-image,gemini-3.1-flash-image,gemini-3-pro-image,gemini-3.1-flash-image-preview,nano-banana-pro-preview',
  ),
  GEMINI_IMAGE_MODEL: Joi.string().allow('').optional(),
  GEMINI_MAX_RETRIES_PER_MODEL: Joi.number().integer().min(1).max(10).default(3),
  COOKIE_DOMAIN: Joi.string().allow('').default(''),
});
